"""initial schema

Revision ID: ced2af5e0bc1
Revises: 
Create Date: 2026-04-07 23:27:10.756281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ced2af5e0bc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('llm_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=False),
    sa.Column('gguf_path', sa.Text(), nullable=False),
    sa.Column('mmproj_path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('quantization', sa.String(length=20), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_tool_use', sa.Boolean(), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('default_top_p', sa.Float(), nullable=False),
    sa.Column('benchmark_tps', sa.Float(), nullable=True),
    sa.Column('benchmark_ttft_ms', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_mode', sa.String(length=20), nullable=False),
    sa.Column('default_llm_model_id', sa.UUID(), nullable=True),
    sa.Column('default_max_steps', sa.Integer(), nullable=False),
    sa.Column('c_puct', sa.Float(), nullable=False),
    sa.Column('rollout_depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_llm_model_id'], ['llm_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bundle_id', sa.String(length=200), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('llm_model_id', sa.UUID(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('c_puct', sa.Float(), nullable=False),
    sa.Column('rollout_depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('output_dir', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_screen_hash', sa.String(length=64), nullable=False),
    sa.Column('target_screen_hash', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details_json', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('step_idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_run_id'), 'edges', ['run_id'], unique=False)
    op.create_index(op.f('ix_edges_source_screen_hash'), 'edges', ['source_screen_hash'], unique=False)
    op.create_index(op.f('ix_edges_target_screen_hash'), 'edges', ['target_screen_hash'], unique=False)
    op.create_table('screens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('screen_id_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('elements_json', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screens_run_id'), 'screens', ['run_id'], unique=False)
    op.create_index(op.f('ix_screens_screen_id_hash'), 'screens', ['screen_id_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screens_screen_id_hash'), table_name='screens')
    op.drop_index(op.f('ix_screens_run_id'), table_name='screens')
    op.drop_table('screens')
    op.drop_index(op.f('ix_edges_target_screen_hash'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_screen_hash'), table_name='edges')
    op.drop_index(op.f('ix_edges_run_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('agent_settings')
    op.drop_table('llm_models')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
